//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreIdConverter.Properties {
    
    // This class provides type-safe access to application settings
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        // Singleton pattern - only one instance of Settings
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        // Static property to access the singleton instance
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        // Theme setting property
        [global::System.Configuration.UserScopedSettingAttribute()]  // This setting is per-user (not per-application)
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]   // Don't step into this code during debugging
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]  // Default value when no saved value exists
        public string Theme {
            get {
                // Read from the underlying settings storage (user.config file)
                return ((string)(this["Theme"]));
            }
            set {
                // Write to the underlying settings storage (user.config file)
                this["Theme"] = value;
            }
        }
    }
}
